
feeds:
  - url: https://example/foo/bar
    regexp:
      - matcher: .*Foo.*
        exclude: .*123p.*|.*XL.*
        download_path: /data/Foo/Bar/
      - matcher: .*Bar.*
        download_path: /data/Foo/AnotherBar

server:
  host: transmission.lan
  port: 80
  rpc_path: /transmission/rpc