
CREATE TABLE IF NOT EXISTS PATTERN_MATCHER (
  URL VARCHAR,
  MATCHER VARCHAR,
  EXCLUDE VARCHAR,
  DOWNLOAD_PATH VARCHAR
);

CREATE TABLE IF NOT EXISTS RSS_ITEM (
  TITLE VARCHAR,
  LINK VARCHAR,
  GUID VARCHAR,
  PUB_DATE TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (LINK)
)